spring:
  application:
    name: AICamp
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        model: deepseek-r1:7b
#?????????
logging:
  level:
    com.zy.aicamp: debug
    org.springframework.ai.chat.client.advisor: debug
